services:
  - type: web
    name: indian-food-app
    env: python
    buildCommand: ""
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: SECRET_KEY
        value: change-this
      - key: DATABASE_URL
        value: sqlite:///grab.db