services:
  - type: web
    name: indian-food-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /healthz
    envVars:
      - key: SECRET_KEY
        value: change-this
      - key: DATABASE_URL
        value: sqlite:////tmp/app.db